### ISSUE TITLE
Update to Tmux 2.0

### ISSUE THREAD

**Issue by ghostandthemachine** [RallySoftware/rally-emacs#48]
Hey @grammati! Is there interest in a PR for an update to the tmux.conf files to work nicely with Tmux 2.0? @esiefkas and I have this sorted in a branch locally so I'm happy to make a PR.

[This](https://gist.github.com/snuggs/800936) resource help us sort things out.

**Comment by grammati** [comment]
Bring it on!

**Comment by ghostandthemachine** [comment]
This is still in the works. Getting different results from OSX to Linux. PR coming soon

**Comment by ghostandthemachine** [comment]
Sorry for the delay. Interestingly 2.0 was not compatible but the next version is... Deleting this issue
